In [1]:
# This script provides a data pre processing template for machine learning models

In [ ]:
# The dataset used here is from a retail company, which shows the data of 10 customers and whether they bought 
# the company's product or no

In [ ]:
# 1. Set working directory, import the libraries and the dataset

In [5]:
# import the libraries
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# set the working directory
os.getcwd()
os.chdir('/Users/poromendro/Desktop')

# import the dataset
dataset = pd.read_csv('Data.csv')

# view the dataset
dataset

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [7]:
# 2. Set the independent and dependent variables

In [8]:
# independent variables
# select values in all the rows of only the first 3 columns
X = dataset.iloc[:, :-1].values

# dependent variable
# select values in all the rows of the last column
Y = dataset.iloc[:, -1].values

In [13]:
# 3. Take care of missing data

In [14]:
# The 'Salary' column has one missing value. We will replace the missing value with the mean of the 'Salary' column

In [16]:
# import SimpleImputter class from Scikit learn library
from sklearn.impute import SimpleImputer

# create an instance of the SimpleImputter class to replace missing value with mean
imputer = SimpleImputer(missing_values = np.nan, strategy = 'mean')

# use the fit method to apply the 'imputer' object to all the numeric columns
imputer.fit(X[:, 1:3])

# use the transform method to replace the missing values with the mean values
X[:, 1:3] = imputer.transform(X[:, 1:3])

# view the 'independent variable' to see if missing values replaced with mean
print(X)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


In [17]:
# 4. Encode categorical data

In [ ]:
# 'Country' column has categories. We need to encode these categories into numbers, so that machine learning models
# can interpret the data

In [20]:
# import 'ColumnTransformer' class from the compose module of sklearn
from sklearn.compose import ColumnTransformer

# import the 'OneHotEncoder' class from the preprocessing module of sklearn
from sklearn.preprocessing import OneHotEncoder

# specify the transformation (encooder), the class (OneHotEncoder) which will carry out the transformation, the
# indexes too apply the encoding towards, and keep the remaining columns by mentioning 'passthrough'
ct = ColumnTransformer(transformers = [('encoder', OneHotEncoder(), [0])], remainder = 'passthrough')

# fit and transform 'ct' to 'X' and convert the output to a numpy array
X = np.array(ct.fit_transform(X))

# encode the dependent variable 'Y'
# import 'LabelEncoder' class from the preprocessing module of sklearn library
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

# fit and transform 
Y = le.fit_transform(Y)

In [35]:
print(X)

[[0.0 1.0 0.0 0.0 44.0 72000.0]
 [1.0 0.0 0.0 1.0 27.0 48000.0]
 [1.0 0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 0.0 1.0 38.0 61000.0]
 [1.0 0.0 1.0 0.0 40.0 63777.77777777778]
 [0.0 1.0 0.0 0.0 35.0 58000.0]
 [1.0 0.0 0.0 1.0 38.77777777777778 52000.0]
 [0.0 1.0 0.0 0.0 48.0 79000.0]
 [1.0 0.0 1.0 0.0 50.0 83000.0]
 [0.0 1.0 0.0 0.0 37.0 67000.0]]


In [36]:
print(Y)

[0 1 0 0 1 1 0 1 0 1]


In [24]:
# 5. Split the dataset into  training and test set

In [33]:
# import 'train_test_split' class from 'model_selection' module of sklearn
from sklearn.model_selection import train_test_split

# split the dataset where 80% is used for training and 20% is used for testing
# random_state = 1 for getting reproducible results
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2, random_state = 1)

In [34]:
print(X_train)

[[1.0 0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 1.0 0.0 40.0 63777.77777777778]
 [0.0 1.0 0.0 0.0 44.0 72000.0]
 [1.0 0.0 0.0 1.0 38.0 61000.0]
 [1.0 0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 0.0 48.0 79000.0]
 [1.0 0.0 1.0 0.0 50.0 83000.0]
 [0.0 1.0 0.0 0.0 35.0 58000.0]]


In [27]:
print(X_test)

[[1.0 0.0 1.0 0.0 30.0 54000.0]
 [0.0 1.0 0.0 0.0 37.0 67000.0]]


In [28]:
print(Y_train)

[0 1 0 0 1 1 0 1]


In [29]:
print(Y_test)

[0 1]


In [30]:
# 6. Feature Scaling

In [43]:
# import 'StandardScaler' class from the preprocessing module of the sklearn library
from sklearn.preprocessing import StandardScaler

# create StandardScaler instance
sc = StandardScaler()

# fit gets the mean and the standard deviation values
# transform applies the formula x-mean(x)/standard deviation(x)
X_train = sc.fit_transform(X_train[:, 4:])

# apply only the transform of X_train to X_test
X_test = sc.transform(X_test[:, 4:])

ValueError: Found array with 0 feature(s) (shape=(8, 0)) while a minimum of 1 is required by StandardScaler.

In [41]:
print(X_train)

[[-0.19159184 -1.07812594]
 [-0.01411729 -0.07013168]
 [ 0.56670851  0.63356243]
 [-0.30453019 -0.30786617]
 [-1.90180114 -1.42046362]
 [ 1.14753431  1.23265336]
 [ 1.43794721  1.57499104]
 [-0.74014954 -0.56461943]]


In [44]:
print(X_test)

[[1.0 0.0 1.0 0.0 30.0 54000.0]
 [0.0 1.0 0.0 0.0 37.0 67000.0]]
